name: blocapp
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=3.3.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.2
  modular_bloc_bind: ^1.0.1
  asuka: ^2.0.0+1
  validatorless: ^1.2.1
  fl_chart: ^0.67.0
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  google_sign_in: ^6.1.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1 
  path_provider: ^2.0.10
  fluttericon: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  isar_generator: ^3.1.0+1
  build_runner: ^2.1.11
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
     - family: JobTimerIcons
       fonts:
         - asset: assets/fonts/JobTimerIcons.ttf
