// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhQQoEF8akWH6LSsTnEBNO5FdBgFkhbt0',
    appId: '1:76375850392:web:446cceb80a093ace4a3fed',
    messagingSenderId: '76375850392',
    projectId: 'diario-de-tarefas',
    authDomain: 'diario-de-tarefas.firebaseapp.com',
    storageBucket: 'diario-de-tarefas.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXpdBspEo2lL7eM_Iv1MmMHgxh7rlBtiA',
    appId: '1:76375850392:android:24c197802993de594a3fed',
    messagingSenderId: '76375850392',
    projectId: 'diario-de-tarefas',
    storageBucket: 'diario-de-tarefas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwv_cZPJoCQdM_m3-68n6qHuUeF4ksm3A',
    appId: '1:76375850392:ios:8c3d26e9f183e2394a3fed',
    messagingSenderId: '76375850392',
    projectId: 'diario-de-tarefas',
    storageBucket: 'diario-de-tarefas.appspot.com',
    iosClientId: '76375850392-c2hhsctmgb2230dbgtv83ifflogm6de4.apps.googleusercontent.com',
    iosBundleId: 'com.brasizza.marcus.blocapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwv_cZPJoCQdM_m3-68n6qHuUeF4ksm3A',
    appId: '1:76375850392:ios:8c3d26e9f183e2394a3fed',
    messagingSenderId: '76375850392',
    projectId: 'diario-de-tarefas',
    storageBucket: 'diario-de-tarefas.appspot.com',
    iosClientId: '76375850392-c2hhsctmgb2230dbgtv83ifflogm6de4.apps.googleusercontent.com',
    iosBundleId: 'com.brasizza.marcus.blocapp',
  );
}
