// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcDlX5P-HnktqTCXSBY_R8HpRa9z7QRcs',
    appId: '1:442208404444:web:6cbd77fd09b67b1c308519',
    messagingSenderId: '442208404444',
    projectId: 'cuidapet-8e9d5',
    authDomain: 'cuidapet-8e9d5.firebaseapp.com',
    databaseURL: 'https://cuidapet-8e9d5.firebaseio.com',
    storageBucket: 'cuidapet-8e9d5.appspot.com',
    measurementId: 'G-LEYSHCSNR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfAflpSfjniyMmR8itD1VUanXdv-fKpDE',
    appId: '1:442208404444:android:c63a9eb82c1db370308519',
    messagingSenderId: '442208404444',
    projectId: 'cuidapet-8e9d5',
    databaseURL: 'https://cuidapet-8e9d5.firebaseio.com',
    storageBucket: 'cuidapet-8e9d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKG4PE9orDMdfTta5Lgtd5sDEYQDwJ7pI',
    appId: '1:442208404444:ios:5ee7f6cc4e047974308519',
    messagingSenderId: '442208404444',
    projectId: 'cuidapet-8e9d5',
    databaseURL: 'https://cuidapet-8e9d5.firebaseio.com',
    storageBucket: 'cuidapet-8e9d5.appspot.com',
    androidClientId:
        '442208404444-re8co00keg5s7c37rug8jjnf5e504mbl.apps.googleusercontent.com',
    iosClientId:
        '442208404444-aintt7041c7uol1q1pu4r2di789pbcjq.apps.googleusercontent.com',
    iosBundleId: 'com.brasizza.marcus.blocapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKG4PE9orDMdfTta5Lgtd5sDEYQDwJ7pI',
    appId: '1:442208404444:ios:5ee7f6cc4e047974308519',
    messagingSenderId: '442208404444',
    projectId: 'cuidapet-8e9d5',
    databaseURL: 'https://cuidapet-8e9d5.firebaseio.com',
    storageBucket: 'cuidapet-8e9d5.appspot.com',
    androidClientId:
        '442208404444-re8co00keg5s7c37rug8jjnf5e504mbl.apps.googleusercontent.com',
    iosClientId:
        '442208404444-aintt7041c7uol1q1pu4r2di789pbcjq.apps.googleusercontent.com',
    iosBundleId: 'com.brasizza.marcus.blocapp',
  );
}
